apiVersion: v1
kind: Service
metadata:
  name: {{ include "xkcd.fullname" . }}-proxy
  labels:
    {{- include "xkcd.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: keda-http-add-on-interceptor-proxy.keda
