kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ include "xkcd.fullname" . }}
spec:
    {{- with .Values.hosts }}
    hosts:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pathPrefixes }}
    pathPrefixes:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    targetPendingRequests: {{ .Values.targetPendingRequests }}
    scaleTargetRef:
        name: {{ include "xkcd.fullname" . }}
        kind: Deployment
        apiVersion: apps/v1
        service: {{ include "xkcd.fullname" . }}
        port: 8080
    replicas:
        min: {{ .Values.autoscaling.http.minReplicas }}
        max: {{ .Values.autoscaling.http.maxReplicas }}
