kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ include "xkcd.fullname" . }}
    {{- with .Values.hosts }}
    hosts:
        {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
    {{- with .Values.hosts }}
    hosts:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    targetPendingRequests: {{ .Values.targetPendingRequests }}
    scaleTargetRef:
        deployment: {{ include "xkcd.fullname" . }}
        service: {{ include "xkcd.fullname" . }}
        port: 8080
    replicas:
        min: {{ .Values.autoscaling.http.minReplicas }}
        max: {{ .Values.autoscaling.http.maxReplicas }}
