version: "2"
run:
  concurrency: 4
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - bodyclose
    - unconvert
    - ineffassign
    - staticcheck
    - copyloopvar
    #- depguard #https://github.com/kedacore/keda/issues/4980
    - dogsled
    - dupl
    - errcheck
    #- funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 80
      statements: 40
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - revive
          - unparam
        path: _test\.go
      - path: pkg/http/
        linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
        path: pkg/net/
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
        path: operator/controllers/http
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
        path: interceptor/metrics/
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
        path: pkg/build/
      # Exclude for utils packages with meaningful package names
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: operator/controllers/util/predicate.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/util/
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kedacore/http-add-on)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      # Exclude gci check for //+kubebuilder:scaffold:imports comments. Waiting to
      # resolve https://github.com/kedacore/keda/issues/4379
      - operator/controllers/http/suite_test.go
      - operator/main.go
