# ko configuration
# See https://ko.build/configuration/ for details

# Preferred over chainguard/static (missing s390x) and distroless/static (12 vs 1 layer)
defaultBaseImage: ghcr.io/wolfi-dev/static:alpine@sha256:de720d589fde216a0b7ebef5ca83ba80e563ac43fedf8c5d9db65e792bc5e3a9

defaultEnv:
  - CGO_ENABLED=0
  - VERSION=HEAD

defaultLdflags:
  - -s -w
  - -X github.com/kedacore/http-add-on/pkg/build.version={{.Env.VERSION}}
  - -X github.com/kedacore/http-add-on/pkg/build.gitCommit={{.Git.FullCommit}}
