apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: OTEL_PROM_EXPORTER_ENABLED
          value: "true"
        - name: OTEL_PROM_EXPORTER_PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.open-telemetry-system:4318"
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "1"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http"
