apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-http-add-on-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-http-add-on-scaler
subjects:
- kind: ServiceAccount
  name: keda-http-add-on-scaler
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-http-add-on-scaler
  namespace: keda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-http-add-on-scaler
subjects:
- kind: ServiceAccount
  name: keda-http-add-on-scaler
  namespace: keda
