apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: external-scaler
    app.kubernetes.io/name: keda-http-add-on
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-http-add-on
  name: keda-http-add-on-external-scaler
  namespace: keda
spec:
  ports:
  - name: grpc
    port: 9090
    targetPort: scaler-grpc
  - name: health
    port: 9091
    targetPort: scaler-health
  selector:
    control-plane: external-scaler
    app: keda-http-add-on
