apiVersion: v1
kind: Service
metadata:
  name: external-scaler
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 9090
    targetPort: grpc
  - name: health
    protocol: TCP
    port: 9091
    targetPort: health
