apiVersion: v1
kind: Service
metadata:
  name: external-scaler
spec:
  selector:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: grpc
