# Example: Plain text placeholder for simple clients
# Use case: CLI tools, simple HTTP clients, or monitoring systems
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: simple-service
spec:
    hosts:
        - simple.example.com
    scaleTargetRef:
        name: simple-backend
        kind: Deployment
        apiVersion: apps/v1
        service: simple-backend
        port: 8080
    replicas:
        min: 0
        max: 10
    scalingMetric:
        concurrency:
            targetValue: 100
    placeholderConfig:
        enabled: true
        refreshInterval: 3
        statusCode: 503
        headers:
            Content-Type: "text/plain; charset=utf-8"
        content: |
            {{.ServiceName}} is currently unavailable.

            The service is scaling up to handle your request.
            Please retry in {{.RefreshInterval}} seconds.

            Namespace: {{.Namespace}}
            Timestamp: {{.Timestamp}}
