# Example: JSON placeholder for API-to-API communication
# Use case: Microservices calling other microservices
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: api-service
spec:
    hosts:
        - api.example.com
    scaleTargetRef:
        name: api-backend
        kind: Deployment
        apiVersion: apps/v1
        service: api-backend
        port: 8080
    replicas:
        min: 0
        max: 10
    scalingMetric:
        concurrency:
            targetValue: 100
    placeholderConfig:
        enabled: true
        refreshInterval: 10
        statusCode: 202  # 202 Accepted - request received but not yet processed
        headers:
            Content-Type: "application/json"
            Retry-After: "10"
            X-Service-Status: "scaling"
        content: |
            {
              "status": "warming_up",
              "service": "{{.ServiceName}}",
              "namespace": "{{.Namespace}}",
              "retry_after_seconds": {{.RefreshInterval}},
              "timestamp": "{{.Timestamp}}",
              "message": "Service is scaling up to handle your request"
            }
