apiVersion: apps/v1
kind: Deployment
metadata:
  name: interceptor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: interceptor
        env:
        - name: OTEL_PROM_EXPORTER_ENABLED
          value: "true"
        - name: OTEL_PROM_EXPORTER_PORT
          value: "2223"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.open-telemetry-system:4318"
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "1"
