name: 'Setup Test Environment'
description: 'Set up prerequisites, Go, Helm, Kind cluster, and build/load Docker images'
inputs:
  kindVersion:
    description: 'Kubernetes version to test'
    required: true
  version:
    description: 'Version tag for Docker images'
    required: true
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt update
        sudo apt install curl make ca-certificates gcc libc-dev -y
      env:
        DEBIAN_FRONTEND: noninteractive

    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: "go.mod"

    - name: Helm install
      uses: Azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

    - name: Create Kind Cluster
      uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      with:
        node_image: kindest/node:${{ inputs.kindVersion }}
        cluster_name: cluster
        version: v0.31.0

    - name: Generate images and push to the cluster
      shell: bash
      run: |
        make docker-build
        kind load docker-image ghcr.io/kedacore/http-add-on-operator:${VERSION} --name cluster
        kind load docker-image ghcr.io/kedacore/http-add-on-interceptor:${VERSION} --name cluster
        kind load docker-image ghcr.io/kedacore/http-add-on-scaler:${VERSION} --name cluster
      env:
        VERSION: ${{ inputs.version }}

    - name: Show Kubernetes version
      shell: bash
      run: kubectl version
