---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-http-add-on-interceptor
  namespace: keda
  labels:
    control-plane: interceptor
    app: keda-http-add-on
    app.kubernetes.io/name: keda-http-add-on
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/part-of: keda-http-add-on
spec:
  replicas: 3
  selector:
    matchLabels:
      control-plane: interceptor
      app: keda-http-add-on
  template:
    metadata:
      labels:
        control-plane: interceptor
        app: keda-http-add-on
      name: keda-http-add-on-interceptor
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: keda-http-add-on-interceptor
      containers:
        - name: interceptor
          image: ghcr.io/kedacore/http-add-on-interceptor:latest
          command:
            - /interceptor
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
          - containerPort: 9090
            name: inter-admin
          - containerPort: 8080
            name: inter-proxy
          env:
          - name: KEDA_HTTP_ROUTING_TABLE_UPDATE_DURATION_MS
            value: "500"
          - name: KEDA_HTTP_CURRENT_NAMESPACE
            value: "keda"
          - name: KEDA_HTTP_PROXY_PORT
            value: "8080"
          - name: KEDA_HTTP_ADMIN_PORT
            value: "9090"
          - name: KEDA_HTTP_CONNECT_TIMEOUT
            value: "500ms"
          - name: KEDA_HTTP_KEEP_ALIVE
            value: "1s"
          - name: KEDA_RESPONSE_HEADER_TIMEOUT
            value: "500ms"
          - name: KEDA_CONDITION_WAIT_TIMEOUT
            value: "20s"
          - name: KEDA_HTTP_DEPLOYMENT_CACHE_POLLING_INTERVAL_MS
            value: "1000"
          - name: KEDA_HTTP_FORCE_HTTP2
            value: "false"
          - name: KEDA_HTTP_MAX_IDLE_CONNS
            value: "100"
          - name: KEDA_HTTP_IDLE_CONN_TIMEOUT
            value: "90s"
          - name: KEDA_HTTP_TLS_HANDSHAKE_TIMEOUT
            value: "10s"
          - name: KEDA_HTTP_EXPECT_CONTINUE_TIMEOUT
            value: "1s"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
