apiVersion: v1
kind: ConfigMap
metadata:
  name: interceptor-placeholder-templates
data:
  # Optional default template used when placeholderConfig.content is not specified
  # This is an HTML example - users can create any format (JSON, XML, plain text, etc.)
  # Users should always set the Content-Type header in their HTTPScaledObject to match their format
  default.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Service Starting</title>
        <meta charset="utf-8">
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                display: flex;
                align-items: center;
                justify-content: center;
                min-height: 100vh;
                margin: 0;
                background: #f5f5f5;
            }
            .container {
                text-align: center;
                padding: 2rem;
                background: white;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                max-width: 400px;
            }
            h1 {
                color: #333;
                margin-bottom: 1rem;
                font-size: 1.5rem;
            }
            .spinner {
                width: 40px;
                height: 40px;
                margin: 1.5rem auto;
                border: 4px solid #f3f3f3;
                border-top: 4px solid #3498db;
                border-radius: 50%;
                animation: spin 1s linear infinite;
            }
            @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
            }
            p {
                color: #666;
                margin: 0.5rem 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{{.ServiceName}} is starting up...</h1>
            <div class="spinner"></div>
            <p>Please wait while we prepare your service.</p>
        </div>
    </body>
    </html>