apiVersion: kustomize.config.k8s.io/v1beta1
kind: TransformerConfig
namePrefix:
  - apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    path: spec/scaleTargetRef/name
  - apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    path: spec/triggers/metadata/scalerAddress
