apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
  {{- range $key, $val := .Labels }}
    {{ $key }}: {{ $val }}
  {{- end }}
spec:
  minReplicaCount: {{ .MinReplicas }}
  maxReplicaCount: {{ .MaxReplicas }}
  pollingInterval: 250
  scaleTargetRef:
    name: {{ .DeploymentName }}
    kind: Deployment
  triggers:
    - type: external
      metadata:
        scalerAddress: {{ .ScalerAddress }}
