name: Publish canary image to GitHub Container Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-repo:
    runs-on: ubuntu-latest
    outputs:
      image-repo: ${{ steps.get_repo.outputs.IMAGE_REPO }}
    steps:
      - name: Get lowercase image repo
        id: get_repo
        run: echo "IMAGE_REPO=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

  build:
    needs: [get-repo]
    uses: ./.github/workflows/template-build-sign.yml
    with:
      version: canary
      image-registry: ghcr.io
      image-repo: ${{ needs.get-repo.outputs.image-repo }}
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
