name: Check the e2e tests DUMMY

on: [push, pull_request]


jobs:
  e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Helm install
        uses: Azure/setup-helm@v1

      - name: Create k8s v1.23 Kind Cluster
        uses: JorTurFer/kind-action@main
        with:
          node_image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
          cluster_name: http-add-on-smoke-tests-cluster

      - name: Run e2e test
        run: |
          ./tests/e2e-test.sh
        env:
          TAG: 0.3.0
