name: Build Images
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [scaler, operator, interceptor]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'
      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10
      - name: Build ${{ matrix.component }}
        run: make ko-build-${{ matrix.component }}
        env:
          VERSION: ${{ github.sha }}
