name: "Stale"

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-slim
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          # Issues
          exempt-issue-labels: "stale-bot-ignore,feature,security,breaking-change,Epic,dependencies,enhancement"
          stale-issue-label: "stale"
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 7 days if no further activity occurs. Thank you
            for your contributions.
          close-issue-message: >
            This issue has been automatically closed due to inactivity.

          # PRs
          days-before-pr-stale: -1 # never mark as stale to preserve all PRs
